export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";

export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const SAVE_USER_DATA = "SAVE_USER_DATA";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
